// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"
	"fiber-g/apps/user/internal/logic"
	"fiber-g/apps/user/internal/svc"
	user2 "fiber-g/apps/user/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user2.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) CreateUser(ctx context.Context, in *user2.CreateUserReq) (*user2.CreateUserResp, error) {
	l := logic.NewCreateUserLogic(ctx, s.svcCtx)
	return l.CreateUser(in)
}
