// Code generated by goctl. DO NOT EDIT!
// Source: dept.proto

package server

import (
	"context"

	"fiber-g/apps/dept/rpc/dept"
	"fiber-g/apps/dept/rpc/internal/logic"
	"fiber-g/apps/dept/rpc/internal/svc"
)

type DeptServer struct {
	svcCtx *svc.ServiceContext
	dept.UnimplementedDeptServer
}

func NewDeptServer(svcCtx *svc.ServiceContext) *DeptServer {
	return &DeptServer{
		svcCtx: svcCtx,
	}
}

func (s *DeptServer) CreateDept(ctx context.Context, in *dept.CreateDeptReq) (*dept.CreateDeptResp, error) {
	l := logic.NewCreateDeptLogic(ctx, s.svcCtx)
	return l.CreateDept(in)
}
