// Code generated by goctl. DO NOT EDIT!
// Source: asset.proto

package server

import (
	"context"

	"fiber-g/apps/asset/asset"
	"fiber-g/apps/asset/internal/logic"
	"fiber-g/apps/asset/internal/svc"
)

type AssetServer struct {
	svcCtx *svc.ServiceContext
	asset.UnimplementedAssetServer
}

func NewAssetServer(svcCtx *svc.ServiceContext) *AssetServer {
	return &AssetServer{
		svcCtx: svcCtx,
	}
}

func (s *AssetServer) CreateAsset(ctx context.Context, in *asset.CreateAssetReq) (*asset.CreateAssetResp, error) {
	l := logic.NewCreateAssetLogic(ctx, s.svcCtx)
	return l.CreateAsset(in)
}
