// Code generated by goctl. DO NOT EDIT!
// Source: asset.proto

package server

import (
	"context"

	"fiber-g/apps/asset/asset"
	"fiber-g/apps/asset/internal/logic"
	"fiber-g/apps/asset/internal/svc"
)

type AssetServer struct {
	svcCtx *svc.ServiceContext
	asset.UnimplementedAssetServer
}

func NewAssetServer(svcCtx *svc.ServiceContext) *AssetServer {
	return &AssetServer{
		svcCtx: svcCtx,
	}
}

func (s *AssetServer) CreateAsset(ctx context.Context, in *asset.CreateAssetReq) (*asset.CreateAssetResp, error) {
	l := logic.NewCreateAssetLogic(ctx, s.svcCtx)
	return l.CreateAsset(in)
}

func (s *AssetServer) CreateProject(ctx context.Context, in *asset.ProjectReq) (*asset.ProjectResp, error) {
	l := logic.NewCreateProjectLogic(ctx, s.svcCtx)
	return l.CreateProject(in)
}

func (s *AssetServer) GetProjectList(ctx context.Context, in *asset.ProjectListReq) (*asset.ProjectListResp, error) {
	l := logic.NewGetProjectListLogic(ctx, s.svcCtx)
	return l.GetProjectList(in)
}

func (s *AssetServer) ImportAssets(ctx context.Context, in *asset.UploadReq) (*asset.UploadResp, error) {
	l := logic.NewImportAssetsLogic(ctx, s.svcCtx)
	return l.ImportAssets(in)
}

// get common assets list
func (s *AssetServer) GetAssetList(ctx context.Context, in *asset.PageReq) (*asset.AssetListResp, error) {
	l := logic.NewGetAssetListLogic(ctx, s.svcCtx)
	return l.GetAssetList(in)
}
