// Code generated by goctl. DO NOT EDIT.
package types

type HealthResp struct {
	Ping string `json:"ping"`
}

type CreateDeptReq struct {
	Name     string `json:"name"`
	ParentId string `json:"parentId"`
	Level    int64  `json:"level"`
}

type CreateDeptResp struct {
	UUID string `json:"uuid"`
}
