// Code generated by goctl. DO NOT EDIT.
package types

type Asset struct {
	ProjectId       string  `json:"projectId"`
	SonProjectId    string  `json:"sonProjectId"`
	PartProjectId   string  `json:"partProjectId"`
	ProjectName     string  `json:"projectName"`
	SonProjectName  string  `json:"sonProjectName"`
	PartProjectName string  `json:"partProjectName"`
	Serial          string  `json:"serial"`
	Name            string  `json:"name"`
	Type            string  `json:"type"`
	Kind            string  `json:"kind"`
	SubDistrict     string  `json:"subDistrict"`
	Brand           string  `json:"brand"`
	Specs           string  `json:"specs"`
	Unit            string  `json:"unit"`
	Params          string  `json:"params"`
	Value           float64 `json:"value"`
	Address         string  `json:"address"`
	Long            string  `json:"long"`
	Lat             string  `json:"lat"`
	ImgUrl          string  `json:"imgUrl"`
	SystemLoginUrl  string  `json:"systemLoginUrl"`
	SystemLoginPwd  string  `json:"systemLoginPwd"`
	IotNetSerial    string  `json:"iotNetSerial"`
	NetStatus       string  `json:"netStatus"`
	EmeterSerial    string  `json:"emeterSerial"`
	EmeterStatus    string  `json:"emeterStatus"`
}

type Project struct {
	Name            string `json:"name"`
	ParentProjectId string `json:"parentProjectId"`
}

type PageInfoReq struct {
	Page     int `json:"page"`
	PageSize int `json:"pageSize"`
}

type ResultWithData struct {
	Code      int32                  `json:"code"`
	Msg       string                 `json:"msg"`
	Data      map[string]interface{} `json:"data"`
	Timestamp int64                  `json:"timestamp"`
}

type ResultWithMsg struct {
	Code      int32  `json:"code"`
	Msg       string `json:"msg"`
	Timestamp int64  `json:"timestamp"`
}
